module(load="imtcp") # needs to be done just once
input(type="imtcp" port="514")

template (name="Remote_Logger" type="string" string="/var/log/remote/%hostname%/secure.log")
action (type="omfile" DynaFile="Remote_Logger")

