---
- name: Deploying a remote log server to rhel-dev02
  hosts: remote_log_server
  become: true
  tasks:
   - name: Ensure correct packages are installed
     ansible.builtin.dnf:
       name: 
         - firewalld
         - rsyslog
       state: latest
   